platform :ios, '13.0'

target 'NBAPP' do
  use_frameworks!

  # Pods for NBAPP
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 7.0'

  target 'NBAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NBAPPUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end


